Adding Tooling & Basic Design
callstack-internal/onboarding-slavik pull request #1
Opened 2022-02-02 17:13 UTC by slavikdenis

2022-02-02 17:26 UTC, dratwas requested changes

2022-02-02 17:26 UTC, dratwas commented on src/screens/DetailScreen.tsx
> +          keyExtractor={item => item.selector}
keyExtractor, renderItem etc shouldn't be an inline function. It forces the whole flatlist to re-render even if it is not necessary because a new reference is passed to flatlist.

2022-02-02 17:26 UTC, dratwas commented on src/screens/HomeScreen.tsx
> +      renderItem={({ item }) => (
Same here ;) Please optimize flatlist

2022-02-03 09:21 UTC, slavikdenis commented on src/screens/DetailScreen.tsx
> +          keyExtractor={item => item.selector}
Oops. Should be good now. Fixed via https://github.com/callstack-internal/onboarding-slavik/pull/1/commits/5e509e0ed03433838faf29979bf5cf3a37dc59f3

2022-02-03 09:22 UTC, slavikdenis commented on src/screens/HomeScreen.tsx
> +      renderItem={({ item }) => (
Fixed via https://github.com/callstack-internal/onboarding-slavik/pull/1/commits/5e509e0ed03433838faf29979bf5cf3a37dc59f3

2022-02-03 10:40 UTC, dratwas approved these changes

2022-02-03 10:45 UTC, merged